apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: hello
spec:
  replicas: 9
  selector:
    run: hello
  strategy:
    rollingParams:
      intervalSeconds: 10
      maxSurge: 1
      maxUnavailable: 1
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: docker.io/openshift/hello-openshift
        imagePullPolicy: Always
        name: hello
      restartPolicy: Always
  triggers:
  - type: ConfigChange
