## User Credentials

For this workshop, you will be interacting with an OpenShift environment
which has been setup to run on a single host. This is a shared environment
which all other workshop attendees will also be using.

Each attendee will login to the OpenShift environment using a separate
user account.

User names are of the form `userXX`, where `XX` starts at the number `01`
and works upward. The password for all user accounts is the same as the
user name.

Please use only the user name you were assigned.

As you work through the exercises you will be given various commands you
need to run from the command line, or you may be asked to enter values
into the web console.

Most of the commands or sample text can be copy/pasted directly. Others
will require modification before they can be used.

If you see a command or sample text with a red border (see below), the
text will require modification before it can be used.

[source,role=copypaste]
----
some command for userXX
----

Typically any substitution required is that for your assigned user name.
Check any adjacent description to qualify what may need to be changed.

Because you are using a shared environment with limited resources, and
quotas are not being enforced, please be considerate of other attendees.
For example, if you experiment with scaling up an application to have
multiple instances, limit yourself to at most three instances and scale it
back down to one instance when you are satisfied it is working as expected.
